In [3]:
# Numpy Basics:
# importing numpy
import numpy as np

In [5]:
# Creating Arrays from scratch:
# create a length-10 integer array filled with 0s
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
# create a 3 x 5 floating point array
np.zeros((3,5), dtype=float)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
# create a 2x10 filled with a single value
np.full((2,10), 23.19)

array([[23.19, 23.19, 23.19, 23.19, 23.19, 23.19, 23.19, 23.19, 23.19,
        23.19],
       [23.19, 23.19, 23.19, 23.19, 23.19, 23.19, 23.19, 23.19, 23.19,
        23.19]])

In [9]:
# create an array with a linear sequence filled with numbers starting at 0 and ending at 20, stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# create an array of five values evenly spaced between 0 and 1:
np.linspace(0,1,5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
# create a 3 x 3 pseudo random values between 0 and 1
np.random.random((3,3))

array([[0.55817672, 0.06700382, 0.52733898],
       [0.46541988, 0.55901202, 0.67559802],
       [0.92704912, 0.67646354, 0.55534645]])

In [13]:
# create a random matrix 3 x 3 with values [0,10)
np.random.randint(0,10,(3,3))

array([[2, 4, 2],
       [1, 4, 8],
       [0, 5, 2]])

In [14]:
# creates an unitilized array of three integers
np.empty(3)

array([3., 2., 1.])